# @package _global_
checkpoint: null

tensorboard: true
auto_cpu_if_no_gpu: true
device: cuda:2
mixed_precision: false
save: true
eval_freq: 1000
eval_iters: 100

hparams:
  batch_size: 128
  epochs: 50

k: 10
feed_layers: null
train_projector: true
use_ema: false
diffae_ckpt_path: /projects/smala3/Saranga/explainability/diffae/checkpoints/bbc_021/last.ckpt
use_reg_loss: false